### ISSUE TITLE
Python 3.9 is no longer supported

### ISSUE THREAD

**Issue by pierreguilmin** [patrick-kidger/jaxtyping#269]
On a fresh Python 3.9.20 install I get the following error:

```shell
>>> import jaxtyping
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.9/site-packages/jaxtyping/__init__.py", line 35, in <module>
    from ._decorator import jaxtyped as jaxtyped
  File ".../.venv/lib/python3.9/site-packages/jaxtyping/_decorator.py", line 29, in <module>
    from typing import (
ImportError: cannot import name 'ParamSpec' from 'typing' (.../uv/python/cpython-3.9.20-macos-aarch64-none/lib/python3.9/typing.py)
```

**Comment by patrick-kidger** [comment]
Ah! Thanks for the report.I'd be happy to take a PR that gates that behind an `if TYPE_CHECKING` block.

**Comment by baluyotraf** [comment]
Hello. I also just encountered this issue. It think it would be nice to fix it using the `typing_extensions` backport instead. I can make a PR for it if you're cool with that.
